# Group Send Noification

## Notify [POST / ]

+ Request (application/json)
    + Attributes
        + url: `tgram://12345678910:DKFJDHKDS-DKwsksdpORUjdsiYerk/-987654321/` (string, optional) - target URL in apprise syntax (https://github.com/caronc/apprise/wiki/URLBasics)
        + setting: `NOTIFYME_TGRAM` (string, optional) - setting name containing one or more target URLs 
        + title: `Service Name: Event Name` (string, required) - message title
        + body: `Some message body here` (string, required) - message body 

+ Response 200 (application/json)
    + Attributes
        + detail: `ok` (string, required, fixed) - default successfull response

+ Response 400 (application/json)
    When no target is provided in the request body (both `url` and `setting` are null) and no default target set up (setting `NOTIFYME_DEFAULT` is missed or incorrect).
    + Attributes
        + detail: `No notification URL setting provided.` (string, required, fixed) - Bad request data provided

+ Response 500 (application/json)
    When the target is not reachable, or any other internal exception is raised while sending a notification.
    + Attributes
        + detail: `Something went wrong: could not send the notification.` (string, required, fixed) - Bad request data provided
